services:
  - type: web
    name: travelhub
    env: static
    buildCommand: |
      cd client
      npm install
      chmod +x node_modules/.bin/react-scripts
      npm run build
    staticPublishPath: client/build
